### ISSUE TITLE
How can I run this in background ?

### ISSUE THREAD

**Issue by vaibhav93** [theycallmeswift/node-mongodb-s3-backup#18]
Right now I need to keep the terminal open to keep this app running

**Comment by theycallmeswift** [comment]
Hey @vaibhav93.  Thanks for reaching out.  This StackOverflow thread has a lot of options for you: http://stackoverflow.com/questions/4018154/node-js-as-a-background-service

Hope that helps!

**Comment by vaibhav93** [comment]
Thanks @theycallmeswift

**Comment by dkoo761** [comment]
In case anyone else needs help with this, I got it working as a background process on startup on OSX using a launch daemon as follows:

NOTE: I'm using a forked version of this repo since the repo currently has a breaking change. Here's my fork if you need it (with instructions): https://github.com/dkoo761/node-mongodb-s3-backup

1) Create a file in /Library/LaunchDaemons called something like your.app.name.plist. The file should contain this (change all the paths + names as needed):

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
  
	<key>Label</key>
	<string>your.app.name.application</string>

	<key>WorkingDirectory</key>
	<string>/path/to/your/json/config/file</string>

	<key>EnvironmentVariables</key>
	<dict>
	  <key>PATH</key>
	  <string>/path/to/node:/path/to/tar:/path/to/mongodump:/path/to/rm</string>
	</dict>
  
	<key>ProgramArguments</key>
	<array>
	  <string>/path/to/mongodb_s3_backup</string>
	  <string>-n</string>
	  <string>your_mongodb_s3_backup_file.json</string>
	</array>
	
	<key>StartCalendarInterval</key>
	<dict>
	  <key>Hour</key>
	  <integer>0</integer>
	  <key>Minute</key>
	  <integer>0</integer>
	</dict>
	
	<key>StandardErrorPath</key>
	<string>/tmp/your.app.name.application.err</string>

	<key>StandardOutPath</key>
	<string>/tmp/your.app.name.application.out</string>	
	
  </dict>
</plist>
```
To find the paths to use above, run these in your terminal:

- for /path/to/node -> run `which node` and leave off the last `/node` part
- for /path/to/tar -> run `which tar` and leave off the last `/tar` part
- for /path/to/mongodump -> run `which mongodump` and leave off the last `/mongodump` part
- for /path/to/rm -> run `which rm` and leave off the last `/rm` part
- for /path/to/mongodb_s3_backup -> which `which mongodb_s3_backup` AND INCLUDE the`/mongodb_s3_backup` part at the end!

The above plist file is using `StartCalendarInterval` to specify the schedule instead of using the `cron` feature built into the package. This is due to the fact that `cron` logic in the package can sometimes trigger the cron job to run twice (which might be related to JS `setTimeout` not being very accurate). **So to be clear, whatever you set for `cron` in the JSON config will be overridden by the `StartCalendarInterval` setting.**

For testing, I suggest using a value for `StartCalendarInterval` that's 1 minute after the current time so you can verify below that's it's running without waiting.

2) Change owner of the file to `root`: `sudo chown root your.app.name.plist`

3) Change group of the file to `wheel`: `sudo chgrp wheel your.app.name.plist`

Running `ls -la` in your terminal, the file listing should now look like this:
`-rw-r--r--   1 root  wheel   <file_size> <date> your.app.name.application.plist`

4) Test the process by running: `sudo launchctl load /Library/LaunchDaemons/your.app.name.application.plist`. This should schedule the backup.

5) Verify the process loaded: `sudo launchctl list | grep your.app.name`. You should see the process name.

6) Stop the process by running: `sudo launchctl unload /Library/LaunchDaemons/your.app.name.application.plist`

7) Verify the process stopped: `sudo launchctl list | grep your.app.name` should not have any output.

8) Restart your machine.

9) Verify the backup process loaded (see step 5 above).

10) After the scheduled time, verify the backup ran: `cat /tmp/your.app.name.application.out`. You should see something like:

```
17 Jul 00:00:00 - [info] Starting mongodump of your-db-name
....lots of mongodump logs....
17 Jul 00:00:30 - [info] Removing /path/to/backup/dir/your-db-name_backup-date.tar.gz
```
